# Generated by Django 5.2.10 on 2026-01-28 21:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(upload_to='audits/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parse_version', models.CharField(default='1.0', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_code', models.CharField(help_text='e.g., 26SP, 25FA', max_length=10)),
                ('course_code', models.CharField(help_text='Base course code only, e.g., ARTS1101', max_length=20, validators=[django.core.validators.RegexValidator(message='Must be base code ABCD1234', regex='^[A-Z]{4}\\d{4}$')])),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('grade_token', models.CharField(blank=True, help_text='e.g., A, A-, B+, IP, AP, W', max_length=10)),
                ('title_raw', models.CharField(blank=True, max_length=200)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='audits.audit')),
            ],
            options={
                'ordering': ['term_code', 'course_code'],
                'unique_together': {('audit', 'term_code', 'course_code')},
            },
        ),
    ]
