# Generated by Django 5.2.10 on 2026-01-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='core_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
